### ISSUE TITLE
Reorganizing interpolation functions

### ISSUE THREAD

**Issue by anchal-physics** [ProjectTorreyPines/GGDUtils.jl#15]
We need to move SD4SOLPS.core_profile_2d() to GGDUtils (along with a helper function check_rho_1d or we can copy this small functionality inside core_profile_2d() to break dependence).

It would be nice to have an overloaded interp function such that:
```
get_edge_profile_n_e = interp(dd.edge_profiles.ggd[1].electrons.density, dd.edge_profiles.grid_ggd[1].space[1])
```
returns a callable function `get_edge_profile_n_e (r, z)` that uses SOLPS data for getting electron density anywhere.

```
rz2rho = interp(dd.equilibirum.time_slice[1])
```
returns a callable function `rz2rho(r, z)` that returns rho value at a given (r, z) using equilibrium data for a chosen time_slice.

Finally, assuming core_profile data has been filled using SD4SOLPS.extrapolate_core, we can use
```
get_core_profile_n_e = interp(dd.core_profiles.profiles_1d[1], "electrons.density")
```
returns a callable function `get_core_profile_n_e(rho)` that provides electron density for given rho.
or
```
get_core_profile_n_e = interp(dd.core_profiles.profiles_1d[1], "electrons.density", rz2rho)
```
returns a callable function `get_core_profile_n_e(r, z)` that provides electron density at given (r, z). Note that we can even overload get_core_profile_n_e using this method.
We can also use the same `rz2rho` for other core_profile .

---

## Tasks

- [x] Reorganize GGDUtils.jl. Create a new file inteprolations.jl to hold interpolation functions.
- [x] Overload `interp(::OMAS.edge_profiles__electrons__density, OMAS.edge_profiles__grid_ggd___space)`
- [x] Overload `interp(::OMAS.equilibrium__time_slice)` returns a conversion function from (r, z) to rho
- [x] Overload `interp(::OMAS.core_profiles__profiles_1d, ::String)` returns 1d interpolation from rho to a quantity
- [x] Overload `interp(::OMAS.core_profiles__profiles_1d, ::String, ::Function)` returns 1d interpolation from (r, z) to a quantity using a rz2rho(r, z) function obtained by `interp(::OMAS.equilibrium__time_slice)`
- [x] Overload `interp(::OMAS.core_profiles__profiles_1d, ::String, ::OMAS.equilibrium__time_slice)` same as above but by using n equilibrium time slice
